### ISSUE TITLE
什么时候考虑支持SVN呢？

### ISSUE THREAD

**Issue by harrybi** [dollarkillerx/easydevops#3]

**Comment by dollarkillerx** [comment]
SVN 我们用过 其实git主要在本系统中作为  一个通知钩子的存在 ,逻辑很简单    在gowith版本中cmd 处理主要是打包 然后是git操作  ,  当git提交后  git server会触发一个通知 到部署服务器上    ,简单的修改就可以适应任意版本控制系统 , 也可以修改server端   当文件打包到服务器就调用client的更新钩子  。目前没有支持svn的打算。您可以自行修改以适用于svn
